import os

class Config:
  SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
  SQLALCHEMY_TRACK_MODIFICATIONS = False
  SQLALCHEMY_ECHO = True
  SECRET_KEY = os.getenv("SECRET_KEY")

  JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
  JWT_TOKEN_LOCATION = ['cookies']
  JWT_COOKIE_SECURE = False
  JWT_COOKIE_CSRF_PROTECT = False
  JWT_ACCESS_COOKIE_PATH = "/"
  JWT_REFRESH_COOKIE_PATH = "/refresh"
  JWT_ACCESS_TOKEN_EXPIRES = 15 * 3600
  JWT_REFRESH_TOKEN_EXPIRES = 24 * 60 * 3600